version: '3.4'
services:
  database:
     image: microsoft/mssql-server-linux:2017-latest
     container_name: 'database'
     hostname: 'sqlserver'
     restart: always
     environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 'Passw0rd1'
     build:  
        dockerfile: Database/Dockerfile
        context: .
     ports:
        - '5433:1433'
     volumes:
        - ./data/mssql:/var/opt/mssql3
   
  