version: '3.4'  

service:
  image: ${DOCKER_REGISTRY-}database
  build:  
    context: .
    dockerfile: Database/Dockerfile
  
sqlserverService:
  image: microsoft/mssql-server-linux:2017-latest
  hostname: 'sqlserver'
  environment:
   ACCEPT_EULA: Y
   SA_PASSWORD: 'Passw0rd1'
  volumes:
     ./data/mssql:/var/opt/mssql3
  ports:
    - '1433:1433'
  expose:
    - '1433'